
alg: BehaviorCloningDiffusion
alg_kwargs:
  bc_all_steps: 10000
  bc_data: pos

optim: Adam
optim_kwargs:
  lr: 0.001

network: ActorPolicy
network_kwargs:
  actor_class: DiffusionMLPActor
  actor_kwargs:
    # output_act: ["import", "torch.nn", "Tanh"]
    hidden_layers: [64, 64]
    ortho_init: True
    dropout: 0.25 # only actor gets dropout sometimes.

    # Diffusion parameters
    diffusion_train_steps: 32
    diffusion_eval_steps: 8
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: "squaredcos_cap_v2"

checkpoint: null

eval_env: mw_reach-v2

dataset: FeedbackBuffer
dataset_kwargs:
  path: datasets/mw/pref/mw_reach-v2_ep2500_n0.3.npz
  batch_size: 96
  segment_length: null # default to 64
  capacity: 2500 # How many segments in the dataset
  label_key: rl_sum
  mode: rank

processor: null

trainer_kwargs: # Arguments given to Algorithm.train
  total_steps: 500000 # The total number of steps to train
  log_freq: 500 # How often to log values
  profile_freq: 500
  eval_freq: 500 # How often to run evals
  eval_fn: eval_policy
  num_eval_envs: 20
  eval_kwargs:
    num_ep: 20 # Number of enviornment episodes to run for evaluation, or -1 if none should be run.
  loss_metric: reward # The validation metric that determines when to save the "best_checkpoint"
  train_dataloader_kwargs:
    num_workers: 0 # Number of dataloader workers.
    batch_size: null

seed: null
